apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  env: dev
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
