apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
labels:
  - pairs:
      env: dev
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
  - path: patch-service.yaml
