apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
  env: prod
resources:
  - ../../base
patches:
  - path: patch-service.yaml
  - path: patch-ingress.yaml
