name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    name: Validate Kustomize overlays
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl and kustomize
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.6'

      - name: Build dev overlay
        run: |
          kubectl kustomize overlays/dev | tee build-dev.yaml > /dev/null

      - name: Build prod overlay
        run: |
          kubectl kustomize overlays/prod | tee build-prod.yaml > /dev/null

  kind-smoke:
    name: Kind smoke test (dev)
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kind
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.24.0
          node_image: kindest/node:v1.29.2

      - name: Apply dev overlay
        run: |
          kubectl apply -k overlays/dev

      - name: Wait for rollout
        run: |
          kubectl -n demo rollout status deploy/dev-web --timeout=120s

      - name: Port-forward and curl
        run: |
          kubectl -n demo port-forward svc/dev-web 18080:80 &
          PF_PID=$!
          sleep 2
          curl -fsS http://localhost:18080/ | head -n1
          kill $PF_PID
